= dotfiles

Configuration for my https://regolith-linux.org/[Regolith Linux] based development environment.

I mostly write https://clojure.org/[Clojure] thorugh https://neovim.io/[Neovim] using my own REPL tooling, https://github.com/Olical/conjure[Conjure], this repository heavily reflects that.

== Installation

 1. Install https://regolith-linux.org/[Regolith Linux].
 2. Import your GPG and SSH keys.
 3. Install Git.
 4. Clone this repository into your home directory.
 5. Execute `init.sh` within this directory.
 6. Enter password and press enter when prompted.
 7. All done!

Feel free to fork and modify this repository to fit your needs!

----
I think there _might_ be an issue with the brew install that means you need to execute `init.sh` twice, but maybe not. Not a huge deal either way, just bear it in mind.
----

== Unlicenced

Find the full http://unlicense.org/[unlicense] in the `UNLICENSE` file, but here's a snippet.

____
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.
____
