= Olical's dotfiles

This is a collection of configuration for things such as https://sw.kovidgoyal.net/kitty/[Kitty] and https://neovim.io/[Neovim] through the Nix package manager and stow for linking the configuration into the right places.

This is designed to be run within an Ubuntu based fistribution, I choose https://regolith-linux.org/[Regolith] as my base since it's minimal and comes with i3 pre-configured.

== Usage

Clone this repo somewhere neat, such as `~/repos/Olical/dotfiles`, `cd` into the directory and execute `script/bootstrap.sh`. This will install `brew` if it's not found then proceed to install all essential packages (as well as a few non-essential but useful ones) and then switch the terminal and shell over to kitty and fish respectively.

It should also run the Neovim first time setup and fetch all of the plugins for you automatically. Once done you can execute the `sync` fish function to update `apt`, `bash` and the Neovim plugins.

Your mileage may vary wildly, this is built for me and may break your entire machine. Be careful, read the code and just take the lines and files you're interested in if you can.

== License

Consider dotfiles unlicensed (https://unlicense.org/), do what you want with anything you want. Feel free to link back if you want, it could help others in the future but I don't mind otherwise.

== Questions?

Feel free to open issues if you're interested in something or tweet me https://twitter.com/OliverCaldwell[@OliverCaldwell].
