font_family      FiraCode Nerd Font
font_size        10

confirm_os_window_close 1
map ctrl+q no_op

# Monokai Pro
background       #2D2A2E
foreground       #FCFCFA
selection_background #5B595C
selection_foreground #FCFCFA
cursor           #FCFCFA
cursor_text_color background

color0  #403E41
color1  #FF6188
color2  #A9DC76
color3  #FFD866
color4  #FC9867
color5  #AB9DF2
color6  #78DCE8
color7  #FCFCFA
color8  #727072
color9  #FF6188
color10 #A9DC76
color11 #FFD866
color12 #FC9867
color13 #AB9DF2
color14 #78DCE8
color15 #FCFCFA
