theme = "monokai_pro"

[editor]
line-number = "relative"
true-color = true
cursorline = true
color-modes = true
bufferline = "multiple"
auto-save = true
scrolloff = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
