#!/bin/sh
#
# JSHint validation. (can be used to prevent committing bad JavaScript)

files=$(git diff --cached --name-only --diff-filter=ACMR -- *.js **/*.js)
pass=true

if [ "$files" != "" ]; then
	for file in ${files}; do
		result=$(jshint ${file})

		if [ "$result" != "" ]; then
			echo $result
			pass=false
		fi
	done
else
	echo "JSHint: Nothing to do here."
fi

if $pass; then
	echo "JSHint: All clean!"
	exit 0
else
	echo "JSHint: Linting errors found!"
	exit 1
fi
